"""
Health State Machine for RICCO AI

Implements the Health State Machine meta-pattern for comprehensive
health monitoring with state transitions, alerting, and auto-recovery.

Part of the Resilience-Aware Architecture DNA.

States:
- HEALTHY: All systems operational
- DEGRADED: Some components experiencing issues but functional
- UNHEALTHY: Critical issues affecting functionality
- RECOVERING: System is recovering from an unhealthy state
"""

import asyncio
import time
from typing import Dict, Any, Optional, List, Callable
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import logging

logger = logging.getLogger(__name__)


# ============================================================================
# Enums and Data Classes
# ============================================================================

class HealthState(str, Enum):
    """Health states for components and system"""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    RECOVERING = "recovering"
    UNKNOWN = "unknown"


class AlertSeverity(str, Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    RESOLVED = "resolved"


@dataclass
class HealthCheckResult:
    """Result of a health check"""
    name: str
    status: HealthState
    message: str
    timestamp: float = field(default_factory=time.time)
    details: Dict[str, Any] = field(default_factory=dict)
    latency_ms: Optional[float] = None


@dataclass
class HealthAlert:
    """Alert generated by health state transitions"""
    id: str
    component: str
    severity: AlertSeverity
    message: str
    previous_state: HealthState
    current_state: HealthState
    created_at: float = field(default_factory=time.time)
    resolved_at: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TransitionRule:
    """Rule for health state transitions"""
    from_state: HealthState
    to_state: HealthState
    condition: Optional[Callable[[Dict], bool]] = None
    action: Optional[Callable[[Dict], None]] = None
    alert_severity: Optional[AlertSeverity] = None
    cooldown_seconds: float = 30.0


# ============================================================================
# Component Health Monitor
# ============================================================================

class ComponentHealthMonitor:
    """
    Health monitor for a single component
    
    Implements:
    - Health check execution
    - State transitions with guards
    - Alert generation
    - Recovery detection
    """
    
    def __init__(
        self,
        name: str,
        check_func: Callable[[], Any],
        check_interval: float = 30.0,
        failure_threshold: int = 3,
        recovery_threshold: int = 2,
        timeout: float = 5.0,
    ):
        self.name = name
        self.check_func = check_func
        self.check_interval = check_interval
        self.failure_threshold = failure_threshold
        self.recovery_threshold = recovery_threshold
        self.timeout = timeout
        
        self._state = HealthState.UNKNOWN
        self._consecutive_failures = 0
        self._consecutive_successes = 0
        self._last_check: Optional[HealthCheckResult] = None
        self._last_state_change: float = 0
        self._check_task: Optional[asyncio.Task] = None
        self._running = False
        
        # Callbacks
        self._on_state_change: List[Callable[[HealthState, HealthState], None]] = []
        self._on_alert: List[Callable[[HealthAlert], None]] = []
    
    @property
    def state(self) -> HealthState:
        return self._state
    
    @property
    def last_check(self) -> Optional[HealthCheckResult]:
        return self._last_check
    
    def on_state_change(self, callback: Callable[[HealthState, HealthState], None]):
        """Register callback for state changes"""
        self._on_state_change.append(callback)
    
    def on_alert(self, callback: Callable[[HealthAlert], None]):
        """Register callback for alerts"""
        self._on_alert.append(callback)
    
    async def check(self) -> HealthCheckResult:
        """Execute health check and return result"""
        start_time = time.time()
        
        try:
            # Execute check with timeout
            if asyncio.iscoroutinefunction(self.check_func):
                result = await asyncio.wait_for(
                    self.check_func(),
                    timeout=self.timeout
                )
            else:
                result = await asyncio.get_event_loop().run_in_executor(
                    None, self.check_func
                )
            
            latency = (time.time() - start_time) * 1000
            
            # Process result
            if isinstance(result, HealthCheckResult):
                check_result = result
                check_result.latency_ms = latency
            elif isinstance(result, dict):
                check_result = HealthCheckResult(
                    name=self.name,
                    status=HealthState(result.get("status", "healthy")),
                    message=result.get("message", "OK"),
                    details=result.get("details", {}),
                    latency_ms=latency,
                )
            elif isinstance(result, bool):
                check_result = HealthCheckResult(
                    name=self.name,
                    status=HealthState.HEALTHY if result else HealthState.UNHEALTHY,
                    message="OK" if result else "Check failed",
                    latency_ms=latency,
                )
            else:
                check_result = HealthCheckResult(
                    name=self.name,
                    status=HealthState.HEALTHY,
                    message="OK",
                    latency_ms=latency,
                )
            
            # Track successes
            self._consecutive_successes += 1
            self._consecutive_failures = 0
            
        except asyncio.TimeoutError:
            check_result = HealthCheckResult(
                name=self.name,
                status=HealthState.UNHEALTHY,
                message=f"Health check timed out after {self.timeout}s",
                latency_ms=self.timeout * 1000,
            )
            self._consecutive_failures += 1
            self._consecutive_successes = 0
            
        except Exception as e:
            check_result = HealthCheckResult(
                name=self.name,
                status=HealthState.UNHEALTHY,
                message=f"Health check error: {str(e)}",
            )
            self._consecutive_failures += 1
            self._consecutive_successes = 0
        
        self._last_check = check_result
        self._update_state()
        
        return check_result
    
    def _update_state(self):
        """Update state based on check results"""
        previous_state = self._state
        
        # State transition logic
        if self._consecutive_failures >= self.failure_threshold:
            new_state = HealthState.UNHEALTHY
        elif self._consecutive_failures > 0:
            new_state = HealthState.DEGRADED
        elif self._consecutive_successes >= self.recovery_threshold:
            new_state = HealthState.HEALTHY
        else:
            new_state = self._state
        
        # Apply transition
        if new_state != self._state:
            self._state = new_state
            self._last_state_change = time.time()
            
            # Notify callbacks
            for callback in self._on_state_change:
                try:
                    callback(previous_state, new_state)
                except Exception as e:
                    logger.error(f"State change callback error: {e}")
            
            # Generate alert
            self._generate_alert(previous_state, new_state)
    
    def _generate_alert(self, previous: HealthState, current: HealthState):
        """Generate alert for state transition"""
        severity = self._determine_severity(previous, current)
        
        alert = HealthAlert(
            id=f"{self.name}-{int(time.time())}",
            component=self.name,
            severity=severity,
            message=f"Health state changed from {previous.value} to {current.value}",
            previous_state=previous,
            current_state=current,
            metadata={
                "consecutive_failures": self._consecutive_failures,
                "consecutive_successes": self._consecutive_successes,
                "last_check_message": self._last_check.message if self._last_check else None,
            },
        )
        
        for callback in self._on_alert:
            try:
                callback(alert)
            except Exception as e:
                logger.error(f"Alert callback error: {e}")
    
    def _determine_severity(
        self,
        previous: HealthState,
        current: HealthState
    ) -> AlertSeverity:
        """Determine alert severity based on transition"""
        if current == HealthState.HEALTHY:
            return AlertSeverity.RESOLVED
        elif current == HealthState.UNHEALTHY:
            return AlertSeverity.CRITICAL
        elif current == HealthState.DEGRADED:
            return AlertSeverity.WARNING
        else:
            return AlertSeverity.INFO
    
    async def start(self):
        """Start periodic health checks"""
        if self._running:
            return
        
        self._running = True
        self._check_task = asyncio.create_task(self._check_loop())
        logger.info(f"Started health monitor for {self.name}")
    
    async def stop(self):
        """Stop health checks"""
        self._running = False
        if self._check_task:
            self._check_task.cancel()
            try:
                await self._check_task
            except asyncio.CancelledError:
                pass
        logger.info(f"Stopped health monitor for {self.name}")
    
    async def _check_loop(self):
        """Periodic health check loop"""
        while self._running:
            try:
                await self.check()
            except Exception as e:
                logger.error(f"Health check error for {self.name}: {e}")
            
            await asyncio.sleep(self.check_interval)


# ============================================================================
# System Health State Machine
# ============================================================================

class SystemHealthStateMachine:
    """
    System-level health state machine
    
    Aggregates component health into system health state with:
    - State transitions with cooldown
    - Alert generation
    - Recovery detection
    - Metrics export
    """
    
    # Transition rules
    TRANSITIONS: Dict[HealthState, List[TransitionRule]] = {
        HealthState.HEALTHY: [
            TransitionRule(HealthState.HEALTHY, HealthState.DEGRADED,
                          alert_severity=AlertSeverity.WARNING),
            TransitionRule(HealthState.HEALTHY, HealthState.UNHEALTHY,
                          alert_severity=AlertSeverity.CRITICAL),
        ],
        HealthState.DEGRADED: [
            TransitionRule(HealthState.DEGRADED, HealthState.HEALTHY,
                          alert_severity=AlertSeverity.RESOLVED),
            TransitionRule(HealthState.DEGRADED, HealthState.UNHEALTHY,
                          alert_severity=AlertSeverity.CRITICAL),
            TransitionRule(HealthState.DEGRADED, HealthState.RECOVERING,
                          alert_severity=AlertSeverity.INFO),
        ],
        HealthState.UNHEALTHY: [
            TransitionRule(HealthState.UNHEALTHY, HealthState.RECOVERING,
                          alert_severity=AlertSeverity.INFO),
            TransitionRule(HealthState.UNHEALTHY, HealthState.DEGRADED,
                          alert_severity=AlertSeverity.WARNING),
        ],
        HealthState.RECOVERING: [
            TransitionRule(HealthState.RECOVERING, HealthState.HEALTHY,
                          alert_severity=AlertSeverity.RESOLVED),
            TransitionRule(HealthState.RECOVERING, HealthState.UNHEALTHY,
                          alert_severity=AlertSeverity.CRITICAL),
        ],
    }
    
    def __init__(self):
        self._state = HealthState.UNKNOWN
        self._components: Dict[str, ComponentHealthMonitor] = {}
        self._alerts: List[HealthAlert] = []
        self._last_transition: float = 0
        self._transition_history: List[Dict[str, Any]] = []
        
        # Callbacks
        self._on_system_state_change: List[Callable[[HealthState, HealthState, Dict], None]] = []
        self._on_system_alert: List[Callable[[HealthAlert], None]] = []
    
    @property
    def state(self) -> HealthState:
        return self._state
    
    def register_component(self, monitor: ComponentHealthMonitor):
        """Register a component health monitor"""
        self._components[monitor.name] = monitor
        
        # Wire up callbacks
        monitor.on_state_change(
            lambda p, c: self._on_component_state_change(monitor.name, p, c)
        )
        monitor.on_alert(self._on_component_alert)
    
    def on_system_state_change(
        self,
        callback: Callable[[HealthState, HealthState, Dict], None]
    ):
        """Register callback for system state changes"""
        self._on_system_state_change.append(callback)
    
    def on_system_alert(self, callback: Callable[[HealthAlert], None]):
        """Register callback for system alerts"""
        self._on_system_alert.append(callback)
    
    def _on_component_state_change(
        self,
        component: str,
        previous: HealthState,
        current: HealthState
    ):
        """Handle component state change"""
        logger.info(f"Component {component} state changed: {previous.value} -> {current.value}")
        self._update_system_state()
    
    def _on_component_alert(self, alert: HealthAlert):
        """Handle component alert"""
        self._alerts.append(alert)
        
        # Keep only recent alerts
        cutoff = time.time() - 3600  # 1 hour
        self._alerts = [a for a in self._alerts if a.created_at > cutoff]
    
    def _update_system_state(self):
        """Update system state based on component states"""
        if not self._components:
            return
        
        # Count states
        state_counts = {s: 0 for s in HealthState}
        for monitor in self._components.values():
            state_counts[monitor.state] += 1
        
        total = len(self._components)
        
        # Determine system state
        if state_counts[HealthState.UNHEALTHY] > 0:
            new_state = HealthState.UNHEALTHY
        elif state_counts[HealthState.DEGRADED] > 0:
            new_state = HealthState.DEGRADED
        elif state_counts[HealthState.RECOVERING] > 0:
            new_state = HealthState.RECOVERING
        elif state_counts[HealthState.HEALTHY] == total:
            new_state = HealthState.HEALTHY
        else:
            new_state = HealthState.UNKNOWN
        
        # Apply transition if valid
        if new_state != self._state:
            self._apply_transition(new_state, state_counts)
    
    def _apply_transition(
        self,
        new_state: HealthState,
        component_states: Dict[HealthState, int]
    ):
        """Apply state transition with validation"""
        previous = self._state
        
        # Find applicable rule
        rules = self.TRANSITIONS.get(previous, [])
        rule = next(
            (r for r in rules if r.to_state == new_state),
            None
        )
        
        if rule:
            # Check cooldown
            elapsed = time.time() - self._last_transition
            if elapsed < rule.cooldown_seconds:
                logger.debug(f"Transition on cooldown for {rule.cooldown_seconds - elapsed:.1f}s")
                return
            
            # Apply transition
            self._state = new_state
            self._last_transition = time.time()
            
            # Execute action
            if rule.action:
                try:
                    rule.action(component_states)
                except Exception as e:
                    logger.error(f"Transition action error: {e}")
            
            # Record history
            self._transition_history.append({
                "from": previous.value,
                "to": new_state.value,
                "timestamp": time.time(),
                "component_states": {s.value: c for s, c in component_states.items()},
            })
            
            # Keep only recent history
            cutoff = time.time() - 86400  # 24 hours
            self._transition_history = [
                h for h in self._transition_history
                if h["timestamp"] > cutoff
            ]
            
            # Generate alert
            if rule.alert_severity:
                alert = HealthAlert(
                    id=f"system-{int(time.time())}",
                    component="system",
                    severity=rule.alert_severity,
                    message=f"System health changed from {previous.value} to {new_state.value}",
                    previous_state=previous,
                    current_state=new_state,
                )
                self._alerts.append(alert)
                
                for callback in self._on_system_alert:
                    try:
                        callback(alert)
                    except Exception as e:
                        logger.error(f"System alert callback error: {e}")
            
            # Notify callbacks
            for callback in self._on_system_state_change:
                try:
                    callback(previous, new_state, component_states)
                except Exception as e:
                    logger.error(f"System state change callback error: {e}")
            
            logger.info(f"System health: {previous.value} -> {new_state.value}")
    
    async def check_all(self) -> Dict[str, HealthCheckResult]:
        """Check all components"""
        results = {}
        tasks = {
            name: monitor.check()
            for name, monitor in self._components.items()
        }
        
        check_results = await asyncio.gather(*tasks.values(), return_exceptions=True)
        
        for (name, monitor), result in zip(self._components.items(), check_results):
            if isinstance(result, Exception):
                results[name] = HealthCheckResult(
                    name=name,
                    status=HealthState.UNHEALTHY,
                    message=f"Check failed: {result}",
                )
            else:
                results[name] = result
        
        self._update_system_state()
        return results
    
    async def start_all(self):
        """Start all component monitors"""
        for monitor in self._components.values():
            await monitor.start()
    
    async def stop_all(self):
        """Stop all component monitors"""
        for monitor in self._components.values():
            await monitor.stop()
    
    def get_status(self) -> Dict[str, Any]:
        """Get current health status"""
        return {
            "system_state": self._state.value,
            "components": {
                name: {
                    "state": monitor.state.value,
                    "last_check": monitor.last_check.message if monitor.last_check else None,
                    "last_check_time": monitor.last_check.timestamp if monitor.last_check else None,
                }
                for name, monitor in self._components.items()
            },
            "active_alerts": [
                {
                    "id": a.id,
                    "component": a.component,
                    "severity": a.severity.value,
                    "message": a.message,
                    "created_at": datetime.fromtimestamp(a.created_at).isoformat(),
                }
                for a in self._alerts
                if not a.resolved_at
            ],
            "transition_count": len(self._transition_history),
        }


# ============================================================================
# Singleton Instance
# ============================================================================

_system_health: Optional[SystemHealthStateMachine] = None


def get_system_health() -> SystemHealthStateMachine:
    """Get or create the system health state machine"""
    global _system_health
    if _system_health is None:
        _system_health = SystemHealthStateMachine()
    return _system_health


# ============================================================================
# Standard Health Checks
# ============================================================================

def create_database_check(db_client, query: str = "SELECT 1") -> Callable:
    """Create a database health check"""
    async def check() -> Dict[str, Any]:
        try:
            if asyncio.iscoroutinefunction(db_client.execute):
                await db_client.execute(query)
            else:
                db_client.execute(query)
            return {"status": "healthy", "message": "Database connection OK"}
        except Exception as e:
            return {"status": "unhealthy", "message": str(e)}
    return check


def create_redis_check(redis_client) -> Callable:
    """Create a Redis health check"""
    async def check() -> Dict[str, Any]:
        try:
            if asyncio.iscoroutinefunction(redis_client.ping):
                await redis_client.ping()
            else:
                redis_client.ping()
            return {"status": "healthy", "message": "Redis connection OK"}
        except Exception as e:
            return {"status": "unhealthy", "message": str(e)}
    return check


def create_http_check(url: str, expected_status: int = 200) -> Callable:
    """Create an HTTP endpoint health check"""
    import httpx
    
    async def check() -> Dict[str, Any]:
        try:
            async with httpx.AsyncClient() as client:
                response = await client.get(url, timeout=5.0)
            
            if response.status_code == expected_status:
                return {"status": "healthy", "message": f"HTTP {url} OK"}
            else:
                return {
                    "status": "degraded",
                    "message": f"HTTP {url} returned {response.status_code}",
                }
        except Exception as e:
            return {"status": "unhealthy", "message": str(e)}
    return check


def create_vector_store_check(store_client, collection: str) -> Callable:
    """Create a vector store health check"""
    async def check() -> Dict[str, Any]:
        try:
            if hasattr(store_client, 'health_check'):
                await store_client.health_check()
            return {
                "status": "healthy",
                "message": f"Vector store {collection} OK",
                "details": {"collection": collection}
            }
        except Exception as e:
            return {"status": "unhealthy", "message": str(e)}
    return check
