"""
RICCO AI Service - Seeds Module
"""

from app.seeds.agent_seeds import (
    AgentSeed,
    AgentCategory,
    ALL_AGENT_SEEDS,
    COMMERCE_AGENTS,
    HEALTH_AGENTS,
    LOGISTICS_AGENTS,
    FUNDING_AGENTS,
    LEGAL_AGENTS,
    SOCIAL_AGENTS,
    CONNECT_AGENTS,
    ID_AGENTS,
    ASSETS_AGENTS,
    BOOKING_AGENTS,
    GYM_AGENTS,
    POS_AGENTS,
    CARGO_AGENTS,
    TRAVEL_AGENTS,
    get_agent_seeds_by_solution,
    get_all_agent_seeds,
    get_agent_seed_by_id,
    TOTAL_AGENTS,
)

from app.seeds.mcp_servers import (
    MCPServerConfig,
    MCPTransport,
    ALL_MCP_SERVERS,
    FILESYSTEM_MCPS,
    DATABASE_MCPS,
    WEB_MCPS,
    AI_MCPS,
    PRODUCTIVITY_MCPS,
    FINANCE_MCPS,
    RICCO_MCPS,
    DEVOPS_MCPS,
    MONITORING_MCPS,
    DOCUMENT_MCPS,
    get_mcp_servers_by_category,
    get_all_mcp_servers,
    get_mcp_server_by_id,
    get_mcp_servers_for_solution,
    TOTAL_MCP_SERVERS,
)

__all__ = [
    # Agent Seeds
    "AgentSeed",
    "AgentCategory",
    "ALL_AGENT_SEEDS",
    "COMMERCE_AGENTS",
    "HEALTH_AGENTS",
    "LOGISTICS_AGENTS",
    "FUNDING_AGENTS",
    "LEGAL_AGENTS",
    "SOCIAL_AGENTS",
    "CONNECT_AGENTS",
    "ID_AGENTS",
    "ASSETS_AGENTS",
    "BOOKING_AGENTS",
    "GYM_AGENTS",
    "POS_AGENTS",
    "CARGO_AGENTS",
    "TRAVEL_AGENTS",
    "get_agent_seeds_by_solution",
    "get_all_agent_seeds",
    "get_agent_seed_by_id",
    "TOTAL_AGENTS",
    
    # MCP Servers
    "MCPServerConfig",
    "MCPTransport",
    "ALL_MCP_SERVERS",
    "FILESYSTEM_MCPS",
    "DATABASE_MCPS",
    "WEB_MCPS",
    "AI_MCPS",
    "PRODUCTIVITY_MCPS",
    "FINANCE_MCPS",
    "RICCO_MCPS",
    "DEVOPS_MCPS",
    "MONITORING_MCPS",
    "DOCUMENT_MCPS",
    "get_mcp_servers_by_category",
    "get_all_mcp_servers",
    "get_mcp_server_by_id",
    "get_mcp_servers_for_solution",
    "TOTAL_MCP_SERVERS",
]
